# Generated by Django 4.0.4 on 2022-05-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_category_subscription_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Абонемент', 'verbose_name_plural': 'Абонемент'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категории'),
        ),
    ]
